In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('House_Price_data.csv')

In [4]:
df.shape

(4600, 18)

In [5]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [6]:
df.dtypes

date                 str
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street               str
city                 str
statezip             str
country              str
dtype: object

In [8]:
df.isna().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
price,4600.0,551962.988473,563834.702547,0.0,322875.00,460943.461539,654962.50,26590000.0
bedrooms,4600.0,3.400870,0.908848,0.0,3.00,3.000000,4.00,9.0
bathrooms,4600.0,2.160815,0.783781,0.0,1.75,2.250000,2.50,8.0
sqft_living,4600.0,2139.346957,963.206916,370.0,1460.00,1980.000000,2620.00,13540.0
sqft_lot,4600.0,14852.516087,35884.436145,638.0,5000.75,7683.000000,11001.25,1074218.0
floors,4600.0,1.512065,0.538288,1.0,1.00,1.500000,2.00,3.5
waterfront,4600.0,0.007174,0.084404,0.0,0.00,0.000000,0.00,1.0
view,4600.0,0.240652,0.778405,0.0,0.00,0.000000,0.00,4.0
condition,4600.0,3.451739,0.677230,1.0,3.00,3.000000,4.00,5.0
sqft_above,4600.0,1827.265435,862.168977,370.0,1190.00,1590.000000,2300.00,9410.0
sqft_basement,4600.0,312.081522,464.137228,0.0,0.00,0.000000,610.00,4820.0
yr_built,4600.0,1970.786304,29.731848,1900.0,1951.00,1976.000000,1997.00,2014.0
yr_renovated,4600.0,808.608261,979.414536,0.0,0.00,0.000000,1999.00,2014.0

In [10]:
data = df.copy()

In [11]:
data['date'] = pd.to_datetime(data['date'])

In [12]:
data.dtypes

date             datetime64[us]
price                   float64
bedrooms                float64
bathrooms               float64
sqft_living               int64
sqft_lot                  int64
floors                  float64
waterfront                int64
view                      int64
condition                 int64
sqft_above                int64
sqft_basement             int64
yr_built                  int64
yr_renovated              int64
street                      str
city                        str
statezip                    str
country                     str
dtype: object

In [13]:
data['Sale_year'] = data['date'].dt.year

In [14]:
data['Sale_month'] = data['date'].dt.month

In [15]:
data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country,Sale_year,Sale_month
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA,2014,5
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA,2014,5
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA,2014,5
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA,2014,5
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA,2014,5

In [16]:
data = df.drop(columns =['date','street','country'])

In [17]:
X = data.drop(columns = ['price'])
y = data['price']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

In [21]:
X_train.shape[0]

3680

In [22]:
X_test.shape[0]

920

In [23]:
X_numerical = X.select_dtypes(include = np.number)
X_categorical = X.select_dtypes(include = 'object')

C:\Users\aamir\AppData\Local\Temp\ipykernel_17024\1257556338.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_categorical = X.select_dtypes(include = 'object')

In [25]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [26]:
X_num_std_scaled = StandardScaler().fit_transform(X_numerical)

In [27]:
X_num_std_scaled

array([[-0.44112227, -0.84320364, -0.82997105, ..., -0.67246372,
        -0.53101376,  1.22167046],
       [ 1.75970468,  0.43280154,  1.56852826, ..., -0.06912828,
        -1.67469295, -0.82569345],
       [-0.44112227, -0.20520105, -0.21736733, ..., -0.67246372,
        -0.1609999 , -0.82569345],
       ...,
       [-0.44112227,  0.43280154,  0.90400897, ..., -0.67246372,
         1.2854179 , -0.82569345],
       [ 0.6592912 , -0.20520105, -0.05123751, ...,  1.5254011 ,
         0.10810108, -0.82569345],
       [-0.44112227,  0.43280154, -0.67422434, ..., -0.67246372,
         0.64630305, -0.82569345]], shape=(4600, 12))

In [28]:
X_num_MinMax_scaled = MinMaxScaler().fit_transform(X_numerical)

In [30]:
X_num_Robust_scaled = RobustScaler().fit_transform(X_numerical)

In [33]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [34]:
ohe = OneHotEncoder()
label_encoder = LabelEncoder()

In [37]:
city_ohe = ohe.fit_transform(X_categorical[['city']]).toarray()

In [38]:
city_ohe

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(4600, 44))

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
model_LR = LinearRegression()

In [41]:
X_train_num, X_test_num, y_train, y_test = train_test_split(
    X_numerical,
    y,
    test_size = 0.20,
    random_state = 1
)

In [42]:
model_LR.fit(X_train_num,y_train)

LinearRegression()

In [43]:
y_pred = model_LR.predict(X_test_num)

In [46]:
y_pred

array([ 489376.70791189,  704333.92088471,  282140.28653487,
        666328.31489388,  786666.12218077,  587680.6674206 ,
        259054.124599  ,  302681.45346365,  449588.28403567,
        492943.03479106,  433966.58080811,  328242.50726177,
        343085.90503219,  745540.89405442,  280575.42922822,
        548294.11890522,  582075.57857154,  460785.34920941,
        453292.76944796,  540542.03488843,  355410.19399155,
        571192.64274981,  649364.28156951,  263900.66271755,
        556723.84263068,  632641.80559123,  276801.12612468,
        275809.62307751,  614211.99054871,  447008.85305189,
        499140.67127374,  891562.43190184,  270488.84208261,
        386161.90601867,  545725.62882067,  447661.58999563,
        281344.3065567 ,  461362.23694911,  663901.8129575 ,
        199220.279068  ,  878689.43708059,  435473.36656992,
        758748.5169012 ,  520866.51938011,  461189.42352764,
        598327.09854082,  526289.64659337,  708498.72006392,
        405285.98640991,  832727.14036818, 1058645.53027838,
        519069.37340433,  393839.49433285,  258309.38316909,
        446751.66493229, 1298960.50799444,  339908.49659378,
        273051.6804784 ,  369922.6518679 ,  680029.84711681,
        350661.13388017,  565499.5654793 ,  410473.47879951,
        893299.4514477 ,  306870.22768024,  326496.7349379 ,
        423747.90789457,  408234.24998172,  412462.99916508,
        688989.94155722,  370633.79753766,  332340.2529598 ,
        631402.64582525,  337611.24411132,  540103.50788226,
        401509.21407511,  335889.74439742,  637820.00137479,
        460860.99094233,  696327.68357363,  301193.38970718,
        365964.41105224,  340313.81024059,  630934.74198538,
        571326.57810405,  660025.2429974 ,  854680.52045595,
        240270.23204061,  350224.96977482,  653874.35684423,
        379624.30318432,  355904.55850765,  339638.24549002,
       1014939.27266005,  693861.84015378,  270487.8889018 ,
        333473.88705125,  698003.52959681,  547844.50826237,
        350517.1403053 ,  482287.34312449,  548040.44548361,
        276173.07857848,  320949.54195513,  404509.58527526,
        426314.9646621 , 1439215.28595659,  582562.31748871,
        424565.95086608,  750874.62770051, 1016062.76369509,
        521970.59700883,  793805.50817117,  501193.2373667 ,
        610980.53978106,  621182.50398795,  321923.06681344,
        701033.9108225 ,  533426.36684789, 1032093.48482179,
        495359.55788213,  381404.79640321,  322630.94080468,
        493299.90052854, 1019919.32652781,  313603.60431489,
        505877.09211649,  555610.33861299,  496153.35325095,
        374687.59084809,  692350.98967023,  426090.9237213 ,
        359695.93762348,  446218.17516104,  805042.7491869 ,
        839971.1602684 ,  884932.92333455,  399414.46310862,
        295856.84846941,  445452.7793496 , 1439481.83992938,
        355313.93076263, 1022050.50658232,  437249.29641627,
        633073.12044613,  510509.21952251,  465378.26355432,
        645688.39135219,  685682.27834318,  587688.70113338,
       1161040.28466177,  344195.30290333,  536905.05543184,
        419452.58716783,  784830.13014475,  572999.52811099,
        605972.11167542,  625656.67208387,  765917.83861466,
        582489.49050238,  362252.84782276, 1707574.44877619,
        348642.45935381,  267368.31454452,  676345.65668341,
        537116.96786769,  726135.15919623,  694620.21142079,
        436052.15371081,  823280.11423979,  939329.88665264,
        479304.33671385,  633555.57148461,  674632.76467243,
        339308.30398172,  672604.63604964,  927845.33565261,
        736285.52516993,  531618.04907661,  518183.13405195,
        366440.53209472,  633568.20719988,  403805.30412439,
        327661.2651023 ,  712122.65883012,  795434.53802077,
       1474706.35891259,  815370.17959417,  599279.84948198,
        805535.90640374,  317830.52906318,  645216.77308065,
        335862.21231415,  310343.86437302,  530090.66064968,
        321334.37237121, 1089525.09479007,  345085.37300917,
        549066.79285346,  481574.96226158,  596482.69241449,
        840945.72772587,  764644.85871167,  658248.4772581 ,
        529221.60942311,  815448.11330488,  422697.51868257,
        107606.8479689 ,  356194.47215901,  404361.30518781,
        285583.16761847,  569480.96826988,  741269.82877885,
        104134.44572446,  336997.94339004,  287585.52740432,
        724485.10478565, 1573088.16717109,  375877.5141544 ,
        627481.21524446,  589893.25953918,  363256.14427493,
        808278.23541539,  314535.32678928,  500990.56895727,
        253743.43766392,  499329.97407497,  415651.3321579 ,
        209198.17607099,  580918.8131184 ,  327050.10314216,
        552984.87909156,  502308.64603144,  272720.8649427 ,
        659622.60373343,  401825.55047034,  462971.0639079 ,
        987492.83101611,  703376.83908296,  785750.28491946,
        498716.7125426 ,  288048.80898792,  573356.6500429 ,
        674525.08893303,  452583.12490643,  692919.20917836,
        482878.14369732,  409711.73881135,  257947.4413983 ,
        954471.461964  ,  439142.98088173,  267929.9131845 ,
        321498.47763847,  374406.99750697, 1102596.79394597,
       1211702.70276198,  635144.88338293,  312600.46176475,
        448705.90282081,  260640.86014463,  608101.14698166,
        453395.4254853 ,  662204.45063201,  511306.44693606,
        358134.31868095,  233022.33793624,  306355.48017235,
        805872.58435407,  432206.83869696,  636256.54764074,
        755037.59709465,  441261.91015816,  314473.26133446,
        304381.66975048,  349358.36830081,  735467.31919375,
        329531.03686967,  585166.78019685,  493967.23816692,
        492425.14521499,  249589.24324596,  305760.50804925,
        967266.99352408,  559750.32323838,  291508.40735245,
        280242.34342461,  666822.61036592,  954757.3688427 ,
        334703.23838149,  579878.95634885,  275610.51433986,
        844705.63443218,  208619.35955808,  763766.39314536,
        508982.53828312,  434563.73730585,  907836.02520107,
        527612.97529783,  449620.12453289,  729322.73030977,
        630903.82402421,  733059.82622219,  576690.61765889,
        515138.52639001,  224583.1678716 ,  504661.28517038,
        811122.56631345,  542873.57056376,  700608.81065481,
        515357.19878838,  277925.36950939,  741250.32866204,
        629476.36917412,  550020.31865361,  711784.94073233,
        439733.65325985,  965506.6140876 ,  571256.2592135 ,
        240025.09927378,  436849.51392008,  694783.03657279,
        261963.5754548 ,  981356.76946159,  477808.30975069,
        745815.11423165,  515748.56965098,  350105.55815473,
        580509.79695518,  406688.16654302,  558274.96167925,
        671726.1140115 , 1003991.38453517,  919445.94991512,
        732014.34068458,  326961.41658547,  668802.95175174,
        126347.09696113,  521044.29026144,  486672.21670392,
        447568.299429  ,  285953.0171644 ,  590525.64632979,
        802016.50031487,  262680.63793135,  661515.22227953,
        964293.40394547, 1604493.15019761,  404729.72025059,
        350927.5028977 ,  393960.71944132,  604708.59546931,
        612817.55516121,  604430.69720607, 1098078.2024194 ,
        347292.41384932,  411584.58948821,  595576.01987681,
        363094.18993527,  602405.18385756,  321732.12183789,
        299061.07468457, 1127155.10138477,  594634.98665475,
        165291.35900822,  507523.38435867,  427408.49779852,
        180038.70059187,  419978.36844785,  280699.64436576,
        620329.92441666,  406179.2656019 ,  496155.82246983,
        462557.48823732,  601511.78030049,  565586.79624395,
        789804.48383243,  225472.85159655,  340339.02139863,
        606140.66676967,  700966.37674056,  356093.42452683,
        501450.83532531,  909169.80469337,  596992.92585524,
        390489.91361151,  518276.16606912,  403325.46281807,
       1035588.4134253 ,  590769.25876464,  221759.91666796,
        356343.12746057,  299228.02513386,  739596.82201509,
        616983.23903047,  504055.84974932,  340990.21462088,
        609082.40622568,  254641.00446597, 1429726.53751673,
        621923.05735866,  340345.54491683,  639990.93478517,
        477328.20630547,  719531.94620219,  491628.67121461,
       1097490.23601616,  502722.4362008 ,  757892.13756436,
        438110.89548996,  384271.68660103,  387564.16898328,
        749200.12786115,  545774.54972181,  196442.04549145,
        559963.00954672,  417564.98152328,  869176.44050232,
        471816.73594303,  475003.18171121,  162840.07628023,
        338676.79045562,  597877.84375579,  533234.53012605,
        361759.36587895,  652150.14114199, 1191397.62734048,
        423530.9169189 ,  381172.23709275,  624227.60478049,
        313807.461543  ,  728768.4998638 ,  454722.12977805,
        638012.84111587,  640633.94970117,  461862.149663  ,
        991638.70081663,  328115.47359081,  842267.31497806,
        267562.84597371,  486022.67030046,  335049.04545769,
        373833.44755707,  409917.56296924,  281776.73501079,
        899591.9439997 ,  685473.66317135,  241581.44627512,
        428979.75627762,  700761.6258989 ,  631766.1387767 ,
        542590.18839739,  288438.73330831,  589393.22750044,
        437109.45257262,  319820.54692326,  453906.51482017,
        305858.08409408,  654173.47120328,  940273.15867381,
        701426.62791717,  478531.7295026 ,  242857.89314951,
       1604560.99145691,  452376.52644947,  447843.69789433,
        433564.64012644,  693160.69453381,  253438.45190536,
        399170.3331101 ,  208846.49556709,  396130.55153472,
        399820.79142207,  299787.24257303,  474819.53045655,
        418183.36335406, 1070143.54618606,  430902.73166218,
        847803.61159109,  609553.17072455,  739582.67601476,
        777167.25394162,  448753.25507617,  178985.2221598 ,
        588927.01366213,  456439.66414248,  658813.30809174,
       1898948.95836889,  171239.06349467,  406974.78315413,
        682800.13513383,  564555.73972705,  236990.5491121 ,
        267710.73757134,  632940.52562293,  396570.67716588,
        407554.86949901,  492294.86059737,  583616.72847169,
        683960.74810333,  268392.74903415,  323403.63066709,
        217474.92328116,  227491.38403833,  707423.52480242,
        568315.59007715,  636224.12475694,  500933.14470102,
        358941.01508069,  656144.08844316,  798418.61634102,
        485340.32251522,  793698.55627363,  470752.05731701,
        738190.91813418,  511996.49945015,  307305.02373792,
        448592.44963775, 1316113.24779079,  495349.64789721,
        657628.85206886,  622769.96167241,  600088.11810813,
        555556.37818338,  271109.79535908,  378947.9267285 ,
        399427.53069617,  768492.25479152,  700216.42571863,
        634026.20629696,  516654.59046405,  379894.2485558 ,
        253024.49290083,  241050.10930732,  440934.59881781,
        507406.29278745,  408908.29941854,  418506.69935048,
        715521.730823  ,  474703.96573347, 1619135.17993301,
        378626.55617932,  422740.01302454, 1118995.98976778,
        307943.64456421,  383877.22893175,  510285.21911539,
        525086.87443224,  499442.07466631, 1116302.22999246,
        707655.39437704,  652825.49082435,  476265.73394313,
        488561.88213525,  564390.81026409,  537340.81633622,
       1136125.34069585,  530788.7238079 , 1527265.47591459,
        513937.50296787,  451209.6638263 ,  678052.56964105,
        593801.04388351,  707794.12346256,  332497.37283232,
        352541.97892742,  667031.99743112,  264703.38313344,
        486069.81719009,  398095.83585917,  528100.97171423,
        541025.22251767,  876611.62065432,  500885.40193288,
        754290.73968931,  512032.08411017,  528845.05405555,
        543488.16854404,  783815.38986627,  879243.91119806,
        672215.05343787,  469925.81246934,  433682.75864311,
        616804.48876224,  332720.48218454,  420303.43361612,
        864868.04471155,  560985.80894308,  280857.65775114,
        803183.60198885, 1495332.11525013,  696694.22487498,
        521369.50721926,  402402.18585729,  509051.26354581,
       1619452.40106007,  708245.23331326,  417359.05655188,
        416530.7730424 ,  429136.88161504,  591941.31903372,
        948769.78650365,  185822.24633308,  509145.85419687,
        676455.87678816, 1387684.77930138, 1157334.22716142,
        578603.32307075,  239980.35571852,  603034.07302873,
        964217.76388864,  328278.36299077,  585811.13272468,
        519267.20679238,  524598.91346913,  347986.33738221,
        399396.36795655,  615167.06932236,  220667.66881326,
        681169.14956606,  636540.11167373,  376353.59470469,
        929318.86372514,  286182.03250079,  888668.34319517,
        627167.51254328,  380414.10916018,  523285.27276333,
        455165.10835249,  418981.14348149,  873065.62892853,
        872999.23917219,  338650.21689196,  458684.74266463,
       1327994.09003678,  396919.80676908,  369682.6731673 ,
        904894.96046984,  782077.75775361, 1190224.47497714,
        958284.34934875,  757259.97556639,  477061.34334472,
        456059.67410609,  856104.75949735,  265240.10633147,
        896791.43731058,  428490.47445525,  312345.83810948,
        649656.02953895,  701922.6147463 ,  321820.56072448,
        370026.56930942,  788428.25252529,  408549.34405045,
        965391.48652949,  521799.02401832,  842538.49842225,
        732911.47542677,  245173.90693039,  693478.19179024,
        534495.73639818,  538613.17097988,  301405.95565429,
        259247.70537017,  878123.46932414,  652978.35267789,
        415875.79650819,  551151.07183519,  249557.73573929,
        432192.51015506,  543887.33510668,  390170.10929846,
       1195921.62123628,  485309.97024962,  275031.81105374,
        342014.92011657,  394073.89371683,  363077.44487661,
        649811.3632217 ,  587114.76997063,  553205.08677061,
        479116.47667352,  377883.13663326,  386553.82438296,
        743055.81556282,  345879.10426593,  698754.65011552,
        659942.37592095,  601864.68866612,  507432.77518241,
       1039960.2204128 ,  635112.04898435,  873452.56372314,
        553757.74186028, 1188365.90802155,  595181.7218943 ,
        376910.64944821,  330145.42365306,  722696.07661504,
        233650.41307892,  336899.38183075,  649688.37254955,
        436463.23975251,  309923.29874947,  336851.6643863 ,
        395048.65490538,  322185.57657646,  246661.55781291,
        542448.6000892 , 1137207.8903362 ,  661293.79685564,
        683576.54364602,  600668.49602477,  443001.54946297,
        696323.95957696,  329393.53116437,  397113.58763061,
        340657.96053039,  417061.62338972,  505428.52844678,
        765021.23434705,  245522.98434225,  696231.4684724 ,
        333004.93863816,  572437.47978024,  484122.27576668,
        317611.41467663,  440720.55882235,  608629.64864358,
        675189.5808693 ,  410419.50315312,  816234.25463163,
        583968.18592163,  342225.45687579,  875423.44523516,
       1043728.11093768,  573887.4842346 ,  514210.77162292,
        582695.44529734,  579818.88234787,  521725.31506207,
        745441.802457  ,  549758.74601279,  389389.08761515,
        435672.54679871,  239830.16392388,  704005.56309522,
        312240.66571967,  611977.21167662,  533129.27808189,
        298552.94702376, 1870585.24999582,  427738.5103747 ,
        453723.01624053, 1319400.38070308,  528715.83203102,
        461198.35616084,  489459.18210066,  475573.02410492,
        426512.43325469,  377329.80182729,  607231.9994659 ,
        803124.63800555,  461755.6106724 ,  337319.49208319,
        895264.38579806,  576832.78020058,  417321.06570093,
        426223.86356808,  247183.3902134 ,  621236.01672601,
        235151.68504796,  690584.72955516,  529301.71082835,
        732703.88034819,  262025.12660394,  387045.42249775,
        492880.70931307,  718814.31201392,  568998.76732706,
        374821.02516853,  371807.76025478,  707617.58603284,
        875686.50054384,  215025.06896734,  443412.57428896,
        521492.18406493,  747683.16824324,  378997.0306996 ,
        763960.43691726,  328382.12169266,  414804.90500544,
        460321.59428687,  645877.78579327,  285019.1225757 ,
        330124.79814295,  652136.76220275,  621714.30914471,
        880073.53639302,  297697.73234545,  364660.35715708,
        209871.73775547,  360899.1613382 ,  349137.23989525,
        765892.55866316,  730200.72582153,  785632.66012319,
        707901.36282214,  457492.23613063,  552203.51209596,
        478387.31574365,  500143.68164843, 1101048.76388466,
        260804.79058366,  389570.81003473,  703352.56941795,
        525459.50201805,  679240.74123372,  404435.11257745,
        794611.12119484,  443922.27198365,  378424.39661635,
        669469.65183379,  462254.90197091,  854614.9885753 ,
        422759.71008475,  749346.89769464,  381682.45859646,
        151455.13928157,  547318.31444448,  394980.1912879 ,
        274390.34368832,  428398.73946221,  344233.28388457,
       1146364.04772527,  388910.98815033,  402534.61594474,
        557854.04409834,  446938.07469247,  469309.99005303,
        547526.71113619,  648086.76307451,  561743.43145176,
        707610.36417132,  554148.59843297,  760421.70888575,
        239981.64606415,  374361.77204398,  471928.2422048 ,
        640749.04771446,  706549.67385878,  456780.71920825,
        259401.67636894,  287577.74351125,  496562.44575393,
        437086.00687165,  433421.56121235,  520803.55159895,
        608839.01235941,  264618.14836436,  872236.40621919,
        424879.42849896, 1216547.69532548,  422777.5358234 ,
        471393.25861257,  318637.71057061,  489821.53688666,
        528097.36361449,  447880.98484587,  697842.99120492,
        598883.81378853,  177030.82411883,  588183.47429225,
        672741.92847085,  438091.02030952,  324659.1663063 ,
        395808.75570127,  372427.07589387,  550312.13193139,
        398565.16179254,  711503.6822382 ,  647599.84609429,
        456457.15484179,  615628.7954915 ,  675548.13064324,
        433569.23868864,  316528.02386753,  815876.2610397 ,
        663068.31489654,  494301.47547138,  688356.5997824 ,
        826687.8554536 ,  740346.18873454,  241266.06115175,
        651227.99000569,  232276.58994214,  298185.58160432,
       1037859.45392206,  394874.65881371,  620654.69579021,
        547221.5741179 ,  327248.78070438,  242334.44528775,
        377144.68816479,  475482.55555841,  392451.0219611 ,
        448137.23010947,  791601.73998438,  326670.12821706,
        391891.31594936,  369568.59350531,  891811.23239728,
        546599.64920252,  553483.51632979,  296343.28207911,
        564930.56198836,  537346.95289224,  980184.52565807,
        546406.97772435,  357968.09371793])

In [45]:
y_test

1351     389000.0
1687    1000000.0
1297     355000.0
2101     390000.0
3920     715000.0
          ...
4487          0.0
2215     315000.0
3634    1165000.0
3531     417000.0
3955     609000.0
Name: price, Length: 920, dtype: float64

In [47]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [49]:
mse = mean_squared_error(y_pred, y_test)
mse

65832396764.36101

In [50]:
mae = mean_absolute_error(y_pred, y_test)
mae

163846.89898477067

In [51]:
r2 = r2_score(y_pred, y_test)

In [52]:
r2

-0.03596228623214803