In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('House_Price_data.csv')

In [6]:
df.shape

(4600, 18)

In [7]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [8]:
df.dtypes

date                 str
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street               str
city                 str
statezip             str
country              str
dtype: object

In [10]:
df.isna().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [11]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
date,4600,70,2014-06-23 00:00:00,142,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,4600.0,NaN,NaN,NaN,551962.988473,563834.702547,0.0,322875.0,460943.461539,654962.5,26590000.0
bedrooms,4600.0,NaN,NaN,NaN,3.40087,0.908848,0.0,3.0,3.0,4.0,9.0
bathrooms,4600.0,NaN,NaN,NaN,2.160815,0.783781,0.0,1.75,2.25,2.5,8.0
sqft_living,4600.0,NaN,NaN,NaN,2139.346957,963.206916,370.0,1460.0,1980.0,2620.0,13540.0
sqft_lot,4600.0,NaN,NaN,NaN,14852.516087,35884.436145,638.0,5000.75,7683.0,11001.25,1074218.0
floors,4600.0,NaN,NaN,NaN,1.512065,0.538288,1.0,1.0,1.5,2.0,3.5
waterfront,4600.0,NaN,NaN,NaN,0.007174,0.084404,0.0,0.0,0.0,0.0,1.0
view,4600.0,NaN,NaN,NaN,0.240652,0.778405,0.0,0.0,0.0,0.0,4.0
condition,4600.0,NaN,NaN,NaN,3.451739,0.67723,1.0,3.0,3.0,4.0,5.0
sqft_above,4600.0,NaN,NaN,NaN,1827.265435,862.168977,370.0,1190.0,1590.0,2300.0,9410.0
sqft_basement,4600.0,NaN,NaN,NaN,312.081522,464.137228,0.0,0.0,0.0,610.0,4820.0
yr_built,4600.0,NaN,NaN,NaN,1970.786304,29.731848,1900.0,1951.0,1976.0,1997.0,2014.0
yr_renovated,4600.0,NaN,NaN,NaN,808.608261,979.414536,0.0,0.0,0.0,1999.0,2014.0
street,4600,4525,2520 Mulberry Walk NE,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,4600,44,Seattle,1573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
statezip,4600,77,WA 98103,148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,4600,1,USA,4600,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data = df.copy()

data['date'] = pd.to_datetime(data['date'])

In [14]:
data['Sale_Year'] = data['date'].dt.year

In [15]:
data['sale_month'] = data['date'].dt.month

In [16]:
data = data.drop(columns=["date", "street", "country"])

In [17]:
data.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,statezip,Sale_Year,sale_month
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,Shoreline,WA 98133,2014,5
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,Seattle,WA 98119,2014,5
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,Kent,WA 98042,2014,5
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,Bellevue,WA 98008,2014,5
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,Redmond,WA 98052,2014,5

In [18]:
data.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'statezip', 'Sale_Year',
       'sale_month'],
      dtype='str')

In [19]:
from sklearn.model_selection import train_test_split

In [21]:
X = data.drop(columns=["price"])
y = data["price"]

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [23]:
X_train.shape[0]

3680

In [24]:
X_test.shape[0]

920

In [27]:
X_numerical = X.select_dtypes(include=np.number)
X_numerical.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,Sale_Year,sale_month
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,2014,5
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,2014,5
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,2014,5
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,2014,5
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,2014,5

In [29]:
X_categorical = X.select_dtypes(include='object')
X_categorical.head()

C:\Users\aamir\AppData\Local\Temp\ipykernel_15452\694472750.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_categorical = X.select_dtypes(include='object')

        city  statezip
0  Shoreline  WA 98133
1    Seattle  WA 98119
2       Kent  WA 98042
3   Bellevue  WA 98008
4    Redmond  WA 98052

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

standard_scaled_X = StandardScaler().fit_transform(X_numerical)
minmax_scaled_X = MinMaxScaler().fit_transform(X_numerical)

In [33]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

one_hot_encoder = OneHotEncoder()
label_encoder = LabelEncoder()

In [34]:
city_ohe = one_hot_encoder.fit_transform(X_categorical[['city']]).toarray()

In [37]:
city_ohe_df = pd.DataFrame(city_ohe, columns=one_hot_encoder.get_feature_names_out(['city']))

In [ ]:
example_labels = label_encoder.fit_transform(["low", "high", "medium", "high"])

Label encoded: [1 0 2 0]

In [ ]:
temp = pd.DataFrame({"city": ["A", "A", "B", "B"], "price": [100, 200, 300, 500]})
city_mean = temp.groupby("city")["price"].mean()
temp["city_target_encoded"] = temp["city"].map(city_mean)
display(temp)

  city  price  city_target_encoded
0    A    100                150.0
1    A    200                150.0
2    B    300                400.0
3    B    500                400.0

In [49]:
X.shape[1]

16

In [55]:
from sklearn.feature_selection import SelectKBest, f_regression

selector = SelectKBest(score_func=f_regression, k=min(5, X_numerical.shape[1]))

selector.fit(X_numerical,y)

SelectKBest(k=5, score_func=<function f_regression at 0x00000236801687C0>)

In [57]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [60]:
X_train_num, X_test_num, y_train_num, y_test = train_test_split(X_numerical, y, test_size=0.2,random_state=1)

In [61]:
model.fit(X_train_num, y_train)

LinearRegression()

In [62]:
model.intercept_

np.float64(4084581.949417089)

In [63]:
model.coef_[0]

np.float64(-53143.736572773276)

In [64]:
y_pred = model.predict(X_test_num)

In [65]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [71]:
mae = mean_absolute_error(y_test,y_pred)
mae

164372.35441128287

In [73]:
mse = mean_squared_error(y_test, y_pred)
mse

65796813530.49216

In [74]:
rmse = np.sqrt(mse)
rmse

np.float64(256508.89561668647)

In [75]:
r2 = r2_score(y_test,y_pred)
r2

0.4604713102999083